version: '3'
services:
  dev:
    image: 'tomcat:9'
    ports:
    - "8080-8082:8080"
    volumes:
    - "/mnt/dev/war:/usr/local/tomcat/webapps"
  qa:
    image: 'tomcat:9'
    ports:
    - "8083-8085:8080"
    volumes:
    - "/mnt/qa/war:/usr/local/tomcat/webapps"
